### PR TITLE
Add numeric sql type inferral override

### PR DESCRIPTION
**Pull request by Daemach**
Added the ability to override the default inferred numeric SQL type ( CF_SQL_NUMERIC ) by adding a module setting in coldbox.cfc ( CF_SQL_BIGINT )

Also fixed an error with the moduleConfig.cfc binder.map() function ( no .to(), which was causing a failure when force=true )

### CODE REVIEW

**Comment by elpete** [comment]
Can you help remind me why this is needed?  In the one off locations where you need to set the SQL type to `BIGINT`, you can pass a query param struct.  Why do you need to change the default?

**Comment by Daemach** [comment]
Every id is an int (tiny, small, int, bigint), not float, and I also store sensor data as ints.  MSSQL takes a **huge** performance hit when using floats.  Even strings are better than cf_sqltype_numeric.  That's what precipitated this thread:  https://boxteam.slack.com/archives/CM8TJL6LD/p1600442114008600  I only use floats in 2 places - currency and barometer readings.  Much easier to pass float SQL types to 2 fields rather than ints to dozens.  On every project.  And this improves performance for quick too.

I use bigint as an sql type because it's safe for tiny, small, int and bigint.  I would rather do good validation to ensure the fields are getting good values than rely on SQL type + database exceptions to catch them.  https://boxteam.slack.com/archives/CM8TJL6LD/p1600617776050100

**Comment by Daemach** [comment]
It also solves this problem, which cannot be avoided by passing in an sql type:  https://boxteam.slack.com/archives/CM8TJL6LD/p1600453499020100?thread_ts=1600443725.010000&cid=CM8TJL6LD, though I think that this is a bug and should also be addressed.

**Comment by elpete** [comment]
Thanks!  This should be out in `qb@8.3.0` shortly.

**Comment by Daemach** [comment]
*cheer*  Thank you!

**Pull request merged**
