### PR TITLE
Added support for Common Table Expressions

### PR DESCRIPTION
**Pull request by dswitzer**
This resolves issue #45 by adding support for CTEs.

### CODE REVIEW

**Comment by dswitzer** [comment]
FYI - I had trouble merging this change into my fork with the other branches I used for the pull requests. I've successfully merged all the changes into my development fork if it helps.

**Comment by dswitzer** [comment]
I've added documentation:

https://github.com/ortus-docs/qb-docs/pull/15

**Comment by elpete** [comment]
The other two pulls have created some merge conflicts.  Can you resolve them please?

**Comment by dswitzer** [comment]
How should I go about this using a pull request?

**Comment by elpete** [comment]
First, pull the current `development` branch.  Then either merge in or rebase off of `development`.  Push the resulting code to your fork and branch.  It may need a force push if you rebase.

**Comment by dswitzer** [comment]
Ok, I think I did it right.

**Comment by elpete** [comment]
It doesn't look like you've pushed the code yet.  You should be pushing it to the same branch on your fork.

**Comment by dswitzer** [comment]
I did push it to the same branch in my fork. It's showing the commit changes up above. It shows the patches for UNION, Derived Tables, etc.

**Comment by dswitzer** [comment]
I just tried to do another pull request and it's warning that it "Can’t automatically merge". 

Should I just manually resolve the conflicts?

**Comment by elpete** [comment]
I just did some conflict merging.  If the tests pass, we should still be good.

**Pull request merged**
