### PR TITLE
Issue 44 add derived tables

### PR DESCRIPTION
**Pull request by dswitzer**
This fixes issue #44 by adding support for derived tables.

### CODE REVIEW

**Comment by elpete** [comment]
This is great!  Thanks for updating the tests, especially.  Can you update the docs here, please?

https://github.com/ortus-docs/qb-docs/blob/master/overview/query-builder/selects.md
https://github.com/ortus-docs/qb-docs/blob/master/overview/query-builder/joins.md

**Comment by dswitzer** [comment]
Shouldn't we wait to document the changes once the code is merged?

**Comment by elpete** [comment]
I’ll merge both once they exist.

**Comment by dswitzer** [comment]
I added the documentation for the derived tables. Instead of adding to the "select" documentation, I just created a new "from" page. I thought it seemed better to split them out since there was so much new documentation.

This also allowed me to document the "from" method better.

https://github.com/ortus-docs/qb-docs/pull/14

**Pull request merged**
